# This is a basic workflow to help you get started with Actions

name: ASP.NET Core

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: '3.1.x'

    - name: Dotnet Build
      run: dotnet build -c Release

    - name: DotNet Pack
      if: github.ref == 'refs/heads/main'
      run: dotnet pack ./DungeonBot/DungeonBot.csproj --configuration Release -o packages --no-build

    - name: DotNet NuGet Push
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push "**/*.nupkg" -k ${{secrets.NUGET_PASSWORD}} -s https://api.nuget.org/v3/index.json
        
    - name: DotNet Publish
      if: github.ref == 'refs/heads/main'
      run: dotnet publish ./Server/DungeonBot.Server.csproj -c Release -o publish --no-build

    - name: Azure WebApp
      if: github.ref == 'refs/heads/main'
      uses: Azure/webapps-deploy@v2
      with:
        publish-profile: ${{secrets.SCM_CREDENTIALS}}
        app-name: DungeonBot
        package: publish
